name: Containerize ASP.NET Core application

on: [push]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
      # Package the app into a linux-x64 container based on the dotnet/aspnet image
      - name: 'Publish docker image'
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=DefaultContainer -p:PublishSingleFile=true -p:SelfContained=true -p:PublishReadyToRun=true -p:ContainerImageTags=latest -p:ContainerImageName=ghcr.io/${{ github.repository_owner }}/space-message-proxy
      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push built container to Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/space-message-proxy:latest
      - name: 'Login via Azure CLI'
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'get apps'
        run: |
          az --version
          az account show
          az config get
          az group list
          az configure --defaults group=rg-sp
          az webapp list --debug
      - name: Set Web App ACR authentication
        uses: FrankStrieter/appservice-settings@v1
        with:
          app-name: 'app-space-message-proxy'
          group-name: 'rg-sp'
          app-settings-json: |
            [
                {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "${{ secrets.GITHUB_TOKEN }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "https://ghcr.io",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value":  "${{ github.actor }}",
                    "slotSetting": false
                },
                {
                    "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
                    "value": false,
                    "slotSetting": false
                }
            ]
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-space-message-proxy'
          resource-group-name: 'rg-sp'
          images: 'ghcr.io/${{ github.repository_owner }}/space-message-proxy:latest'
      
      
